#!/usr/bin/env bash
#Install the ufw firewall and setup rules

sudo ufw disable
sudo apt-get -y install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw

sudo apt-get -y install ufw
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
